version: "3.4"

services:
  seafoodapi:
    image: lephuminh/seafoodapi
    # build:
    #   context: .
    #   dockerfile: SeafoodApi/Dockerfile
  db:
    image: lephuminh/seadb
  nginx:
    image: lephuminh/seafoodweb
