version: "3.4"

services:
  seafoodapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  db:
    container_name: Seafood
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - type: volume
        source: seafood
        target: /var/opt/mssql
    # environment:
    #   SA_PASSWORD: "Lpm@2302"
    #   ACCEPT_EULA: "Y"
  nginx:
    ports:
      - 80:80
    volumes:
      #   - ../SeafoodWeb/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
volumes:
  seafood:
